# This file was generated by GoReleaser. DO NOT EDIT.
class Kiln < Formula
  desc ""
  homepage ""
  version "0.41.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dalvarado/kiln/releases/download/0.41.0/kiln-darwin-0.41.0.tar.gz"
    sha256 "7d2ba0b3b9d9fbc498da4c1e578390c379679baff74ede544d6820bbf4b2f768"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dalvarado/kiln/releases/download/0.41.0/kiln-linux-0.41.0.tar.gz"
      sha256 "fd3c6df72378204f8dbb95b84f78e026586ee4f81887cd4210e01909c73ef99f"
    end
  end

  def install
    bin.install "kiln"
  end

  test do
    system "#{bin}/kiln --version"
  end
end
