# This file was generated by GoReleaser. DO NOT EDIT.
class Kiln < Formula
  desc ""
  homepage ""
  version "0.42.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/dalvarado/kiln/releases/download/0.42.0/kiln-darwin-0.42.0.tar.gz"
    sha256 "2eb20cef906634933acf6253bb682049e2e2ede5609dfe99af7ae82c788ba111"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/dalvarado/kiln/releases/download/0.42.0/kiln-linux-0.42.0.tar.gz"
      sha256 "086945be0647e6bd39cb9642fea27b4db18e4deb5019d6c34adb521adb16dfff"
    end
  end

  def install
    bin.install "kiln"
  end

  test do
    system "#{bin}/kiln --version"
  end
end
