# For documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
release:
  github:
    owner: pivotal-cf
    name: kiln
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  ldflags:
  - -X "main.version={{.Version}}"
archives:
  - id: github
    format: binary
    name_template: "kiln-{{ .Os }}-{{ .Version }}"
  - id: homebrew
    format: "tar.gz"
    name_template: "kiln-{{ .Os }}-{{ .Version }}"
    format_overrides:
      - goos: windows
        format: zip

signs:
  -
    id: brew
    signature: "${artifact}_sig"
    cmd: gpg2

    # command line arguments for the command
    #
    # to sign with a specific key use
    # args: ["-u", "<key id, fingerprint, email, ...>", "--output", "${signature}", "--detach-sign", "${artifact}"]
    #
    # defaults to `["--output", "${signature}", "--detach-sign", "${artifact}"]`
    args: ["--output", "${signature}", "${artifact}"]


    # which artifacts to sign
    #
    #   checksum: only checksum file(s)
    #   all:      all artifacts
    #   none:     no signing
    #
    # defaults to `none`
    artifacts: all

    # IDs of the artifacts to sign.
    # Defaults to all.
    # If `artifacts` is checksum, this fields has no effect.
    ids:
      - homebrew
    

brews:
  - name: kiln
    github:
      owner: pivotal-cf
      name: kiln
    folder: HomebrewFormula
    ids:
      - homebrew
    test: |
      system "#{bin}/kiln --version"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
